export const slides = [
  {
    imageSrc: "/img/s_1.webp",
    containerClass: "bg-[#EE3770]",
    imageClass: "w-[600px] md:w-[430px]",
    shopLink: "/",
    headingClass: "font-roboto text-[27px] font-medium text-white",
    subheadingClass: "font-roboto text-[37px] font-bold text-white",
    textClass: "font-roboto text-[15px] text-white",
    buttonClass: "",
    heading: "New Arrival",
    subheading: "Women Fashion",
    text: "Last call for upto 25%",
  },
  {
    imageSrc: "/img/s_2.webp",
    containerClass: "bg-[#7A316F]",
    imageClass: "w-[600px] md:w-[430px]",
    shopLink: "/",
    headingClass: "font-roboto text-[27px] font-medium text-white",
    subheadingClass: "font-roboto text-[37px] font-bold text-white",
    textClass: "font-roboto text-[15px] text-white",
    buttonClass: "",
    heading: "Latest Trending",
    subheading: "Fashion Wear",
    text: "Last call for upto 35%",
  },
  {
    imageSrc: "/img/s_3.webp",
    containerClass: "bg-[#723DA6]",
    imageClass: "w-[600px] md:w-[430px]",
    shopLink: "/",
    headingClass: "font-roboto text-[27px] font-medium text-white",
    subheadingClass: "font-roboto text-[37px] font-bold text-white",
    textClass: "font-roboto text-[15px] text-white",
    buttonClass: "",
    heading: "New Trending",
    subheading: "Kids Fashion",
    text: "Last call for upto 15%",
  },
  {
    imageSrc: "/img/s_4.webp",
    containerClass: "bg-[#FDC200]",
    imageClass: "w-[600px] md:w-[430px]",
    shopLink: "/",
    headingClass: "font-roboto text-[27px] font-bold text-primary",
    subheadingClass: "font-roboto text-[37px] font-bold text-primary",
    textClass: "font-roboto text-[15px] text-primary",
    buttonClass: "",
    heading: "Latest Trending",
    subheading: "Electronics Items",
    text: "Last call for upto 45%",
  },
  {
    imageSrc: "/img/s_5.webp",
    containerClass: "bg-[#21AD61]",
    imageClass: "w-[600px] md:w-[430px]",
    shopLink: "/",
    headingClass: "font-roboto text-[27px] font-medium text-white",
    subheadingClass: "font-roboto text-[37px] font-bold text-white",
    textClass: "font-roboto text-[15px] text-white",
    buttonClass: "",
    heading: "Super Deals",
    subheading: "Home Furniture",
    text: "Last call for upto 24%",
  },
];

export const bannersData = [
  {
    imagePath: "/img/banner.webp",
    className: "basis-[100%] w-full",
    imageClass: "w-full h-[100%]",
    path: "/",
  },
];
export const multipleBannersData = [
  {
    imagePath: "/img/banner-sm-8.jpg",
    className: "px-10",
    imageClass: " w-full h-[100%]",
    path: "/",
  },
  {
    imagePath: "/img/banner-sm-9.jpg",
    className: "px-10",
    imageClass: " w-full h-[100%]",
    path: "/",
  },
  {
    imagePath: "/img/banner-sm-10.jpg",
    className: "px-10",
    imageClass: "w-full h-[100%]",
    path: "/",
  },
  // containerClass:"justify-between"
];
